package:
  name: ess
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
  run:
    - matplotlib
    - pooch
    - scippneutron>=0.5

test:
  imports:
    - ess
    - ess.wfm
    - ess.amor
    - ess.reflectometry
  requires:
    # - ipympl
    # - mantid
    - pytest
    # - pandoc
    # - pythreejs
    # - python-graphviz
    # - sphinx
    # - sphinx-book-theme<0.3
    # - sphinx-copybutton
    # - nbsphinx
    # - pip
  source_files:
    - tests/
    # - docs/
  commands:
    - python -m pytest -v tests
    # - python docs/make_docs.py

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  script:
    # - pip install  https://files.pythonhosted.org/packages/04/51/4b4a0740fbde50408a2f956cbb190bdc01f1c7a562627e7f102b6a30d9b4/sphinx_autodoc_typehints-1.17.0-py3-none-any.whl
    # - pip install  https://files.pythonhosted.org/packages/9d/b4/761a6da7e1dedf793a6c3410cf362e2b61092a8fd8267d5ebc88e71f1fc5/orsopy-0.0.5-py2.py3-none-any.whl
    - pip install .

about:
  home: https://github.com/scipp/ess
  license: BSD-3-Clause
  summary: Neutron scattering tools for the European Spallation Source (ESS)
  description: Neutron scattering tools for Data Reduction bespoke to ESS facility and instruments
  dev_url: https://github.com/scipp/ess
  doc_url: https://scipp.github.io/ess
