package:
  name: ess
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - sphinx>=1.6
    - sphinx_rtd_theme
    - gitpython
  run:
    - scippneutron {{ scippneutron }}
    - tifffile
    - astropy
    - matplotlib
    - ipywidgets
    - scipy

test:
  imports:
    - scipp
    - ess
    - ess.v20
    - ess.v20.imaging
  requires:
    - pytest
  source_files:
    - tests/
  commands:
    - python -m pytest -v

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  script:
    - python setup.py install

about:
  home: https://github.com/scipp/ess
  license: BSD-3-Clause
  summary: Neutron scattering tools for the European Spallation Source (ESS)
  description: Neutron scattering tools for Data Reduction bespoke to ESS facility and instruments
  dev_url: https://github.com/scipp/ess
  doc_url: https://scipp.github.io/ess
