package:
  name: ess
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
  run:
    - astropy
    - ipywidgets
    - matplotlib
    - pooch
    - scippneutron>=0.4.2
    - scipy
    - tifffile

test:
  imports:
    - ess
    - ess.wfm
    - ess.amor
    - ess.reflectometry
  requires:
    - ipympl
    - mantid-framework
    - pytest
    - pandoc
    - pythreejs
    - python-graphviz
    - sphinx
    - sphinx-book-theme
    - sphinx-copybutton
    - nbsphinx
    - pip
    - pip:
      - sphinx-autodoc-typehints>=1.17.0
  source_files:
    - tests/
    - docs/
  commands:
    - python -m pytest -v tests
    - python docs/make_docs.py

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  script:
    - pip install .

about:
  home: https://github.com/scipp/ess
  license: BSD-3-Clause
  summary: Neutron scattering tools for the European Spallation Source (ESS)
  description: Neutron scattering tools for Data Reduction bespoke to ESS facility and instruments
  dev_url: https://github.com/scipp/ess
  doc_url: https://scipp.github.io/ess
