name: ess-docs-build

channels:
  - conda-forge
  - mantid
  - scipp
  - nodefaults

dependencies:
  - ipympl<0.9  # plots to not show up in the docs with version 0.9
  - mantid
  - nbsphinx
  - pandoc
  - pooch
  - pytest
  - pythreejs
  - python-graphviz
  - scippneutron>=0.5
  - sphinx
  - sphinx-book-theme<0.3  # custom buttons in top bar do not work with version 0.3
  - sphinx-copybutton
  - pip
  - pip:
    - sphinx-autodoc-typehints>=1.17.0
    - orsopy
