parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > ess > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  tags:
    include:
      - '*.*.*'

schedules:
  - cron: "0 0 * * *"
    displayName: 'Nightly dev build'
    branches:
      include:
        - 'main'
    always: false


pr: none


extends:
  template: pipelines/stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp'
    gh_pages_subdirectory: 'ess'
    noarch: true
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'ess-developer.yml'
    package: true
    deploy: true
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:  # nightly
      conda_label: 'dev'
    ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:  # tagged release
      conda_label: 'main'
      release: true
