name: Build

on:
  workflow_call:

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install flake8 yapf==0.30.0
      - run: yapf --recursive --in-place .
      - run: flake8 .
      - run: |
          find . -type f -not -path '.git/*' -exec sed -ri "s/[0-9]{4} (Scipp contributors)/$(date +%Y) \1/g" {} +
          git diff --exit-code
      - uses: stefanzweifel/git-auto-commit-action@v4

  conda_build:
    needs: formatting
    runs-on: ubuntu-latest
    env:
      DOCS_HTML_DIR: ${{ github.workspace }}/docs_html
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # history required so cmake can determine version
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install --channel conda-forge --yes conda-build mamba boa
      - run: conda mambabuild --channel conda-forge --channel scipp --no-anaconda-upload --override-channels --output-folder conda/package conda

      - uses: actions/upload-artifact@v2
        with:
          name: conda-package-ess
          path: conda/package/*/ess*.tar.bz2

      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: ${{ env.DOCS_HTML_DIR }}
