name: Deploy

on:
  workflow_call:
    secrets:
      anaconda_token:
        required: true

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      conda_label: ${{ startsWith(github.ref, 'refs/tags/') && 'main' || 'dev' }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install -c conda-forge --yes anaconda-client
      - uses: actions/checkout@v2  # Need to checkout repo so github-pages-deploy-action works
      - uses: actions/download-artifact@v2
      - run: anaconda --token ${{ secrets.anaconda_token }} upload --user scipp --label ${{ env.conda_label }} $(ls conda-package-*/*/*.tar.bz2)

      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: DocumentationHTML
          # Note: If this is a release, it will not deploy to the top level folder.
          # The next scheduled main build will update that.
          target-folder: ${{ env.conda_label == 'main' && format('release/{0}', github.ref_name) || '' }}
          single-commit: true
          clean-exclude: release
