name: Weekly and Release

on:
  release:
    types: [published]
  schedule:
    - cron: "0 2 * * 4"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}  # required for conda env

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Run this before any other commands so that git diff does not pick up formatting changes.
      - run: |
          find . -type f -not -path '.git/*' -exec sed -ri "s/[0-9]{4} (Scipp contributors)/$(date +%Y) \1/g" {} +
          git diff --exit-code
      - run: pip install flake8 nb-clean==2.1.0 yapf==0.30.0
      - run: find . -type f -regex '.*\.ipynb' | xargs nb-clean clean --remove-empty-cells --preserve-cell-metadata
      - run: yapf --recursive --in-place .
      - run: flake8 .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic formatting

  build:
    needs: formatting
    runs-on: ubuntu-latest
    env:
      DOCS_HTML_DIR: ${{ github.workspace }}/docs_html
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # history required so cmake can determine version
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install --channel conda-forge --yes conda-build mamba boa
      - run: conda mambabuild --channel conda-forge --channel scipp --no-anaconda-upload --override-channels --output-folder conda/package conda

      - uses: actions/upload-artifact@v2
        with:
          name: conda-package-ess
          path: conda/package/*/ess*.tar.bz2

      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: ${{ env.DOCS_HTML_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      conda_label: ${{ startsWith(github.ref, 'refs/tags/') && 'main' || 'dev' }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda install -c conda-forge --yes anaconda-client
      - uses: actions/checkout@v2  # Need to checkout repo so github-pages-deploy-action works
      - uses: actions/download-artifact@v2
      - run: anaconda --token ${{ secrets.ANACONDATOKEN }} upload --user scipp --label ${{ env.conda_label }} $(ls conda-package-*/*/*.tar.bz2)

      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: DocumentationHTML
          # Note: If this is a release, it will not deploy to the top level folder.
          # The next scheduled main build will update that.
          target-folder: ${{ env.conda_label == 'main' && format('release/{0}', github.ref_name) || '' }}
          single-commit: true
          clean-exclude: release
