name: Weekly and Release

on:
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: scipp/ess/.github/workflows/build.yml@try_github_actions

  # deploy:
  #   needs: build
  #   uses: ./.github/workflows/deploy.yml@v1
